{
  "good morning": "bondia",
  "good afternoon": "botarde",
  "good evening": "bonoite",
  "goodbye": "adeus",
  "see you tomorrow": "até aban",
  "see you later": "até logu",
  "how are you?": "di'ak ka lae?",
  "what is your name?": "ita-boot-nia naran saida?",
  "my name is": "ha'u-nia naran",
  "where are you from?": "ita-boot hosi ne'ebé?",
  "I am from": "ha'u hosi",
  "nice to meet you": "kontente hasoru ita-boot",
  "thank you": "obrigadu",
  "you're welcome": "nada",
  "excuse me": "ho lisensa",
  "sorry": "deskulpa",
  "what is this?": "ne'e saida?",
  "where is it?": "iha ne'ebé?",
  "when?": "bainhira?",
  "why?": "tanbasá?",
  "how?": "oinsá?",
  "who?": "sé?",
  "what time is it?": "tuku hira ona?",
  "today": "ohin loron",
  "yesterday": "horisehik",
  "tomorrow": "aban",
  "now": "agora",
  "later": "orsida",
  "I'm going to work": "ha'u ba servisu",
  "I'm eating": "ha'u han hela",
  "I'm studying": "ha'u estuda hela",
  "I'm sleeping": "ha'u toba hela",
  "I'm resting": "ha'u deskansa hela",
  "I'm hungry": "ha'u hamlaha",
  "I'm thirsty": "ha'u hamrook",
  "the food is delicious": "hahán ne'e gostu",
  "can I have some water?": "bele fó bee mai ha'u?",
  "do you speak Tetun?": "ita-boot ko'alia Tetun?",
  "I don't understand": "ha'u la kompriende",
  "please speak slowly": "favór ida ko'alia neineik",
  "how do you say ... in Tetun?": "oinsá ita-boot dehan ... iha Tetun?",
  "can you repeat that?": "bele repete ne'e?",
  "God willing": "se Maromak hakarak",
  "welcome": "benvindu",
  "cheers": "saúde",
  "happy birthday": "feliz loron moris",
  "congratulations": "parabens",
  "it's hot": "ne'e manas",
  "it's cold": "ne'e malirin",
  "it's raining": "ne'e udan daudaun",
  "how much is this?": "ne'e nia folin hira?",
  "that's expensive": "ne'e karun",
  "can you give me a discount?": "bele fó deskontu ruma?",
  "I'm sick": "ha'u moras",
  "I need a doctor": "ha'u presiza doutór",
  "where is the hospital?": "ospitál iha ne'ebé?",
  "where is the bus stop?": "parajen autokarru nian iha ne'ebé?",
  "how much is the fare?": "tarifa nia folin hira?",
  "can you take me to...?": "bele ita-boot lori ha'u ba...?",
  "I have a meeting": "ha'u iha enkontru ida",
  "I'm looking for a job": "ha'u buka hela servisu ida",
  "what's your profession?": "ita-boot-nia profisaun nu'udar saida?",
  "my family": "hau-nia família",
  "I'm married": "ha'u kaben-na'in",
  "I'm single": "ha'u klosan",
  "I have children": "ha'u iha oan",
  "I'm happy": "ha'u kontente",
  "I'm sad": "ha'u triste",
  "I'm tired": "ha'u kole",
  "I'm excited": "ha'u animadu",
  "help!": "ajuda!",
  "call the police!": "bolu polísia!",
  "there's been an accident": "akontese ona asidente ida",
  "turn right": "fila ba liman loos",
  "turn left": "fila ba liman karuk",
  "go straight": "ba loos",
  "where is the nearest...?": "... besik-liu ne'e iha ne'ebé?",
  "I agree": "ha'u konkorda",
  "I disagree": "ha'u la-konkorda",
  "in my opinion": "tuir hau-nia hanoin",
  "every day": "loroloron",
  "sometimes": "dala-ruma",
  "traditional house": "uma lisan",
  "betel nut": "bua",
  "bride price": "barlake",
  "teacher": "manorin",
  "play sports": "joga desportu sira"
}
