{
  "good morning": "bondia",
  "good afternoon": "botardi",
  "good evening": "bonoiti",
  "goodbye": "adeus",
  "see you tomorrow": "até amanyá",
  "see you later": "ate logu",
  "how are you?": "diak ka lae?",
  "what is your name?": "ita naran saida?",
  "my name is": "hau naran",
  "where are you from?": "ita hosi nebee?",
  "I am from": "hau hosi",
  "nice to meet you": "kontenti hasoru ita",
  "thank you": "obrigadu",
  "you're welcome": "nada",
  "excuse me": "lisensa",
  "sorry": "deskulpa",
  "what is this?": "nee saida?",
  "where is it?": "iha nebee?",
  "when?": "bainhira?",
  "why?": "tansaa?",
  "how?": "oinsaa?",
  "who?": "see?",
  "what time is it?": "tuku hira?",
  "today": "ohin loron",
  "yesterday": "horiseik",
  "tomorrow": "aban",
  "now": "agora",
  "later": "orsida",
  "I'm going to work": "hau baa servisu",
  "I'm eating": "hau haan hela",
  "I'm studying": "hau estuda hela",
  "I'm sleeping": "hau toba hela",
  "I'm resting": "hau deskansa hela",
  "I'm hungry": "hau hamlaha",
  "I'm thirsty": "hau hamrook",
  "the food is delicious": "hahaan nee gostu",
  "can I have some water?": "bele foo bee?",
  "do you speak Tetun?": "ita koalia Tetun?",
  "I don't understand": "hau la kompriende",
  "please speak slowly": "favór ida koalia neineik",
  "how do you say ... in Tetun?": "oinsaa dehan ... iha Tetun?",
  "can you repeat that?": "bele repete?",
  "God willing": "se Maromak hakarak",
  "welcome": "bemvindu",
  "cheers": "saude",
  "happy birthday": "parabens",
  "congratulations": "parabens",
  "it's hot": "rai manas",
  "it's cold": "rai malirin",
  "it's raining": "udan tau",
  "how much is this?": "nee folin hira?",
  "that's expensive": "nee karun",
  "can you give me a discount?": "bele fo desc ount?",
  "I'm sick": "hau moras",
  "I need a doctor": "hau presiza doutór",
  "where is the hospital?": "ospitál iha nebee?",
  "where is the bus stop?": "paragem autokarru iha nebee?",
  "how much is the fare?": "selu hira?",
  "can you take me to...?": "bele lori hau ba...?",
  "I have a meeting": "hau iha enkontru",
  "I'm looking for a job": "hau buka servisu",
  "what's your profession?": "ita nia profisaun saida?",
  "my family": "hau nia família",
  "I'm married": "hau kaben ona",
  "I'm single": "hau solteiro/solteira",
  "I have children": "hau iha oan",
  "I'm happy": "hau kontenti",
  "I'm sad": "hau tristi",
  "I'm tired": "hau kole",
  "I'm excited": "hau animadu",
  "help!": "tulun!",
  "call the police!": "bolu polísia!",
  "there's been an accident": "iha asidente",
  "turn right": "fila ba liman loos",
  "turn left": "fila ba liman karuk",
  "go straight": "baa loos deit",
  "where is the nearest...?": "iha nebee ... nebee besik liu?",
  "I agree": "hau konkorda",
  "I disagree": "hau la konkorda",
  "in my opinion": "tuir hau nia hanoin",
  "every day": "loro-loron",
  "sometimes": "dala ruma",
  "traditional house": "uma lulik",
  "betel nut": "bua",
  "bride price": "barlake",
  "teacher": "profesór/a",
  "play sports": "halimar desportu",
}